// ---------------------------------------------------------------------------
// Society events, stored on this device (localStorage) until Supabase
// arrives in Phase 7. Shared by /calendar (manage) and home (preview).
// ---------------------------------------------------------------------------

export type SimpleEvent = {
  id: string;
  title: string;
  /** YYYY-MM-DD */
  dateIso: string;
  /** As written, e.g. "7:30 malam" — may be "" */
  timeText: string;
  /**
   * A free note for this day, e.g. "kena tempah kerusi" / "要先订椅子".
   *
   * 2026-07-28, user: "点了进去也没办法 add event 或者写 note". Optional so every
   * event stored before this change still loads.
   */
  note?: string;
};

const EVENTS_KEY = "minit.events";

export function loadEvents(): SimpleEvent[] {
  try {
    const raw = localStorage.getItem(EVENTS_KEY);
    const arr = raw ? (JSON.parse(raw) as SimpleEvent[]) : [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

export function saveEvents(events: SimpleEvent[]): void {
  try {
    localStorage.setItem(EVENTS_KEY, JSON.stringify(events));
  } catch {
    // storage unavailable — events just won't persist
  }
}

export function sortedByDate(events: SimpleEvent[]): SimpleEvent[] {
  return [...events].sort((a, b) => a.dateIso.localeCompare(b.dateIso));
}

/** Every event on one day, in the order they were added. */
export function eventsOnDay(events: SimpleEvent[], dayIso: string): SimpleEvent[] {
  return events.filter((e) => e.dateIso === dayIso);
}

/** A new event with a generated id. Callers still have to persist it. */
export function makeEvent(input: {
  title: string;
  dateIso: string;
  timeText?: string;
  note?: string;
}): SimpleEvent {
  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    title: input.title.trim(),
    dateIso: input.dateIso,
    timeText: (input.timeText ?? "").trim(),
    note: input.note?.trim() ? input.note.trim() : undefined,
  };
}

/** WhatsApp announcement text for one event. */
export function eventWhatsappText(ev: SimpleEvent): string {
  return [
    `📣 ${ev.title}`,
    `Tarikh / 日期 / date: ${ev.dateIso}${ev.timeText ? ` · ${ev.timeText}` : ""}`,
    ...(ev.note ? [ev.note] : []),
    "Jumpa anda di sana! / 到时见! / See you there!",
    "— dijana oleh Minit / generated by Minit",
  ].join("\n");
}
