// ---------------------------------------------------------------------------
// Society events.
//
// 2026-08-23: these are no longer ONLY on this device. J's UX list, root cause
// B — the calendar, the hand-over batches and the deadlines all lived in one
// browser's localStorage, so signing in on another computer showed a society
// with nothing in it. `events_meetings` had existed since the first migration
// and had RLS policies; it simply had no insert anywhere in the codebase.
//
// The shape below is unchanged and localStorage is still the WORKING copy —
// it is what makes the calendar instant and what keeps it usable when the save
// fails. The database is the durable copy, and `mergeEvents` is how the two
// meet. See src/app/calendar/actions.ts.
// ---------------------------------------------------------------------------

export type SimpleEvent = {
  id: string;
  title: string;
  /** YYYY-MM-DD */
  dateIso: string;
  /** As written, e.g. "7:30 malam" — may be "" */
  timeText: string;
  /**
   * A free note for this day, e.g. "kena tempah kerusi" / "要先订椅子".
   *
   * 2026-07-28, user: "点了进去也没办法 add event 或者写 note". Optional so every
   * event stored before this change still loads.
   */
  note?: string;
};

const EVENTS_KEY = "minit.events";

export function loadEvents(): SimpleEvent[] {
  try {
    const raw = localStorage.getItem(EVENTS_KEY);
    const arr = raw ? (JSON.parse(raw) as SimpleEvent[]) : [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

export function saveEvents(events: SimpleEvent[]): void {
  try {
    localStorage.setItem(EVENTS_KEY, JSON.stringify(events));
  } catch {
    // storage unavailable — events just won't persist
  }
}

export function sortedByDate(events: SimpleEvent[]): SimpleEvent[] {
  return [...events].sort((a, b) => a.dateIso.localeCompare(b.dateIso));
}

/** Every event on one day, in the order they were added. */
export function eventsOnDay(events: SimpleEvent[], dayIso: string): SimpleEvent[] {
  return events.filter((e) => e.dateIso === dayIso);
}

/** A new event with a generated id. Callers still have to persist it. */
export function makeEvent(input: {
  title: string;
  dateIso: string;
  timeText?: string;
  note?: string;
}): SimpleEvent {
  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    title: input.title.trim(),
    dateIso: input.dateIso,
    timeText: (input.timeText ?? "").trim(),
    note: input.note?.trim() ? input.note.trim() : undefined,
  };
}

/** WhatsApp announcement text for one event. */
export function eventWhatsappText(ev: SimpleEvent): string {
  return [
    `📣 ${ev.title}`,
    `Tarikh / 日期 / date: ${ev.dateIso}${ev.timeText ? ` · ${ev.timeText}` : ""}`,
    ...(ev.note ? [ev.note] : []),
    "Jumpa anda di sana! / 到时见! / See you there!",
    "— dijana oleh Minit / generated by Minit",
  ].join("\n");
}

/**
 * The device's events and the organisation's events, as one list.
 *
 * WHY A UNION AND NOT A REPLACE. Both sides can hold something the other has
 * never seen: this device may have events typed while the save was failing (or
 * before an organisation was chosen at all), and the organisation may have
 * events another committee member added from their own phone. Taking either
 * side wholesale silently deletes the other's work — and a deleted event is a
 * meeting nobody turns up to.
 *
 * On a genuine collision — the same id on both sides — the REMOTE wins. That is
 * the copy every other device will also see, so preferring it makes the
 * committee converge on one answer instead of each device insisting on its own.
 *
 * Ordering is by date, so the merged list reads as a calendar rather than as
 * two lists stapled together.
 */
export function mergeEvents(
  local: readonly SimpleEvent[],
  remote: readonly SimpleEvent[],
): SimpleEvent[] {
  const byId = new Map<string, SimpleEvent>();
  for (const e of local) byId.set(e.id, e);
  for (const e of remote) byId.set(e.id, e);
  return sortedByDate([...byId.values()]);
}

/** Shape guard for events arriving from the database or from localStorage. */
export function isSimpleEvent(value: unknown): value is SimpleEvent {
  if (typeof value !== "object" || value === null) return false;
  const e = value as Record<string, unknown>;
  return (
    typeof e.id === "string" &&
    e.id !== "" &&
    typeof e.title === "string" &&
    typeof e.dateIso === "string" &&
    /^\d{4}-\d{2}-\d{2}$/.test(e.dateIso) &&
    typeof e.timeText === "string" &&
    (e.note === undefined || typeof e.note === "string")
  );
}
