// GENERATED BY `npm run legal:sync` — DO NOT EDIT BY HAND.
// Source of truth: legal/terms-of-use-BM-EN.md, legal/privacy-notice-BM-EN.md.
// Edit the markdown, run the script, commit both. src/legal/documents.test.ts
// fails if this file and the markdown disagree.
//
// Why this exists at all: src/app/(legal)/ must show these documents word for
// word, and a file read at request time may not be in the deployment. See
// scripts/sync-legal.mjs.

/** legal/terms-of-use-BM-EN.md — verbatim. */
export const TERMS_MARKDOWN = `# SYARAT PENGGUNAAN / TERMS OF USE — Minit

> **DRAF — 2026-08-03. Belum disemak oleh peguam.**
> **DRAFT — not reviewed by a lawyer.** Fill every \`[[ ]]\` first.
>
> Ini bukan templat SaaS biasa. Minit menghasilkan **dokumen undang-undang**
> (minit mesyuarat, resit, borang eROSES). Dua fasal di bawah — Fasal 3
> (semakan manusia) dan Fasal 6 (had tanggungan) — adalah yang paling penting,
> dan sengaja ditulis supaya jujur, bukan supaya melindungi kami sepenuhnya.

---

# BAHAGIAN 1 — BAHASA MALAYSIA

## 1. Apa itu Minit

Minit ialah alat bantu. Ia membaca dokumen yang anda muat naik dan
**menghasilkan draf**: minit mesyuarat, resit, pek AGM, dan padanan medan
eROSES.

**Minit bukan setiausaha syarikat, bukan juruaudit, dan bukan penasihat
undang-undang atau cukai.**

## 2. Siapa boleh guna

Anda mesti berumur sekurang-kurangnya 18 tahun dan diberi kuasa oleh
pertubuhan anda untuk mengendalikan rekodnya.

## 3. ⚠ Semakan manusia adalah wajib — fasal terpenting

**Setiap dokumen yang dihasilkan oleh Minit adalah DRAF sehingga seorang
manusia menyemak dan mengesahkannya.**

- AI boleh tersalah baca tulisan tangan.
- AI boleh terlepas satu baris.
- Minit menandakan medan yang ia tidak pasti (**Tolong semak**) dan medan yang
  tidak ada dalam nota (**Tiada dalam nota**) — **ia tidak pernah meneka**.
- Semua pengiraan wang dilakukan oleh kod, bukan oleh AI.

**Anda bertanggungjawab terhadap apa yang anda failkan.** Menekan "Sahkan"
bermakna anda telah membacanya dan ia betul. Nama dan tarikh anda muncul pada
baris audit dokumen itu kerana sebab ini.

## 4. Nombor resit

Minit mengeluarkan nombor resit yang **berturutan dan tidak boleh diubah**
bagi setiap pertubuhan. Setelah dikeluarkan, nombor resit tidak boleh dipadam
atau diubah — melalui aplikasi mahupun oleh kami. Ini adalah reka bentuk yang
disengajakan: resit adalah dokumen undang-undang.

Jika anda sudah menggunakan buku resit kertas, tetapkan nombor permulaan anda
**sebelum** mengeluarkan resit pertama. Selepas itu ia dikunci.

## 5. Pelepasan cukai

Minit **tidak akan** mencetak apa-apa yang menunjukkan derma boleh ditolak
cukai melainkan pertubuhan anda telah menetapkan status pengecualian cukai
yang diluluskan (Seksyen 44(6)). Menetapkan status itu adalah pengakuan anda
bahawa pertubuhan anda benar-benar memilikinya. **Kami tidak mengesahkannya.**

## 6. Had tanggungan

Setakat yang dibenarkan undang-undang:

- Minit disediakan **"sebagaimana adanya"**.
- Kami **tidak menjamin** bahawa dokumen yang dihasilkan akan diterima oleh
  JPPM, LHDN, bank, atau mana-mana pihak berkuasa.
- Kami tidak bertanggungjawab terhadap denda, penalti, penyahdaftaran, atau
  kerugian akibat dokumen yang **anda failkan tanpa menyemaknya**.
- Jumlah tanggungan agregat kami tidak melebihi **[[jumlah yang anda bayar
  kepada kami dalam 12 bulan sebelumnya]]**.

**Kami tidak mengecualikan tanggungan bagi penipuan, kecuaian melampau, atau
apa-apa yang tidak boleh dikecualikan di sisi undang-undang.**

## 7. Data anda kekal milik anda

Rekod pertubuhan anda adalah milik pertubuhan anda. Anda boleh memadamkan
pertubuhan anda pada bila-bila masa; ini memadam baris pangkalan data dan fail
storan. **[[Eksport data: lihat Fasal 9 — SAHKAN SETELAH CIRI ITU SIAP]]**

Pemprosesan data peribadi tertakluk kepada **Notis Perlindungan Data Peribadi**
kami.

## 8. Penggunaan yang dilarang

Jangan gunakan Minit untuk menghasilkan dokumen palsu, memuat naik data yang
anda tiada kuasa untuk memprosesnya, atau cuba memintas had penggunaan AI.

## 9. Had penggunaan AI

Setiap tindakan AI dikira terhadap kuota pertubuhan anda. **Permintaan yang
kami tolak kerana ia di luar skop tidak akan mengurangkan kuota anda.**
Baki kuota sentiasa dipaparkan.

## 10. Penamatan

Anda boleh berhenti pada bila-bila masa. Kami boleh menggantung akaun yang
melanggar syarat ini, dan akan memaklumkan sebabnya.

## 11. Undang-undang yang mentadbir

Undang-undang **Malaysia**. Mahkamah **[[bandar]]**.

**Versi: [[tarikh]] · Hubungi: [[emel]]**

---

# PART 2 — ENGLISH

## 1. What Minit is

Minit is an assistive tool. It reads documents you upload and **produces
drafts**: meeting minutes, receipts, AGM packs, and eROSES field mappings.

**Minit is not a company secretary, not an auditor, and not a legal or tax
adviser.**

## 2. Who may use it

You must be at least 18 and authorised by your organisation to handle its
records.

## 3. ⚠ Human review is mandatory — the most important clause

**Every document Minit produces is a DRAFT until a human reviews and confirms it.**

- AI can misread handwriting.
- AI can miss a line.
- Minit flags fields it is unsure about (**Please check**) and fields absent
  from the notes (**Not in the notes**) — **it never guesses**.
- All money arithmetic is done by code, not by AI.

**You are responsible for what you file.** Pressing "Confirm" means you have
read it and it is correct. Your name and the date appear on the document's
audit line for exactly this reason.

## 4. Receipt numbers

Minit issues **sequential, non-editable** receipt numbers per organisation.
Once issued, a receipt number cannot be deleted or altered — not through the
app, and not by us. This is deliberate: receipts are legal documents.

If you already keep a paper receipt book, set your starting number **before**
issuing your first receipt. After that it is locked.

## 5. Tax deductibility

Minit will **not** print anything implying donations are tax-deductible unless
your organisation has set an approved tax-exempt status (Section 44(6)).
Setting that status is your representation that your organisation actually
holds it. **We do not verify it.**

## 6. Limitation of liability

To the extent permitted by law:

- Minit is provided **"as is"**.
- We **do not warrant** that generated documents will be accepted by JPPM,
  LHDN, a bank, or any authority.
- We are not liable for fines, penalties, deregistration, or losses arising
  from documents **you filed without reviewing them**.
- Our aggregate liability will not exceed **[[amounts you paid us in the
  preceding 12 months]]**.

**We do not exclude liability for fraud, gross negligence, or anything that
cannot lawfully be excluded.**

## 7. Your data stays yours

Your organisation's records belong to your organisation. You may delete your
organisation at any time; this removes database rows and storage files.
**[[Data export: see clause 9 — CONFIRM ONCE THE FEATURE EXISTS]]**

Processing of personal data is governed by our **Personal Data Protection Notice**.

## 8. Prohibited use

Do not use Minit to produce false documents, to upload data you have no
authority to process, or to attempt to bypass AI usage limits.

## 9. AI usage limits

Each AI action counts against your organisation's quota. **Requests we decline
as out of scope do not reduce your quota.** Your remaining quota is always shown.

## 10. Termination

You may stop at any time. We may suspend accounts that breach these terms, and
will tell you why.

## 11. Governing law

The laws of **Malaysia**. Courts of **[[city]]**.

**Version: [[date]] · Contact: [[email]]**

---

> **Nota / Note:** Terbitkan sebagai \`/terms\`, tambah ke \`PUBLIC_PATHS\` dalam
> \`src/proxy.ts\`, dan pautkan dari borang pendaftaran bersama notis privasi.
> Publish as \`/terms\`, add to \`PUBLIC_PATHS\`, link from the sign-up form
> alongside the privacy notice.
`;

/** Short hash of the text above. This is what a person's consent is recorded
 *  against, so an edited clause is visibly a different version. */
export const TERMS_VERSION = "52c5ff6e84a8";

/** legal/privacy-notice-BM-EN.md — verbatim. */
export const PRIVACY_MARKDOWN = `# NOTIS PERLINDUNGAN DATA PERIBADI / PERSONAL DATA PROTECTION NOTICE

> **DRAF — 2026-08-03. Belum disemak oleh peguam. Jangan terbitkan sebelum
> ruang \`[[ ]]\` diisi dan seorang peguam menyemaknya.**
> **DRAFT — not yet reviewed by a lawyer. Do not publish until every \`[[ ]]\`
> placeholder is filled and a lawyer has reviewed it.**
>
> Bahasa Malaysia didahulukan seperti dikehendaki oleh Seksyen 7 Akta
> Perlindungan Data Peribadi 2010 (notis bertulis dalam Bahasa Kebangsaan
> **dan** Bahasa Inggeris).

---

# BAHAGIAN 1 — BAHASA MALAYSIA

## 1. Siapa kami

Minit dikendalikan oleh **[[nama entiti undang-undang]]**, **[[No. Pendaftaran]]**,
beralamat di **[[alamat]]** ("kami").

Hubungi kami tentang data peribadi: **[[emel privasi]]**

## 2. Dua peranan yang berbeza — sila baca bahagian ini

Minit mengendalikan dua jenis data yang berlainan, dan peranan undang-undang
kami berbeza bagi setiap satu.

**(a) Data akaun anda — kami ialah PENGAWAL DATA (data controller).**
Alamat emel anda, pertubuhan yang anda sertai, peranan anda, dan rekod
penggunaan AI. Kami yang menentukan mengapa dan bagaimana data ini diproses.

**(b) Dokumen dan rekod pertubuhan anda — kami ialah PEMPROSES DATA (data processor).**
Nota mesyuarat, buku derma, nama penderma, nombor telefon, nombor kad
pengenalan, perlembagaan, senarai ahli jawatankuasa. **Pertubuhan anda ialah
pengawal data bagi maklumat ini.** Kami hanya memprosesnya bagi pihak
pertubuhan, mengikut arahan pertubuhan.

> **Jika anda seorang penderma** dan mahu tahu apa yang disimpan tentang anda,
> atau mahu ia dipadam — sila hubungi **pertubuhan yang mengeluarkan resit
> anda**, bukan kami. Merekalah pengawal data. Kami akan membantu pertubuhan
> memenuhi permintaan anda.

## 3. Data apa yang kami proses

| Jenis | Contoh | Peranan kami |
|---|---|---|
| Data akaun | emel, kata laluan (disulitkan), peranan | Pengawal |
| Data pertubuhan | nama pertubuhan, no. pendaftaran, cawangan | Pengawal |
| Dokumen dimuat naik | foto nota mesyuarat, halaman buku derma, perlembagaan | Pemproses |
| Data penderma | nama, telefon, jumlah, tujuan, tarikh | Pemproses |
| Rekod penggunaan | bilangan tindakan AI, tarikh — **tanpa kandungan** | Pengawal |

**Kami TIDAK merekodkan kandungan dokumen anda di dalam log sistem.**
Rekod penggunaan hanya mengandungi nombor pengenalan pertubuhan, kod tindakan
pendek, dan tarikh.

## 4. Data peribadi sensitif

Sesetengah maklumat yang diproses melalui Minit mungkin merupakan **data
peribadi sensitif** di bawah Seksyen 4 APDP 2010 — contohnya, rekod derma
kepada sebuah pertubuhan keagamaan boleh menunjukkan kepercayaan agama
seseorang.

Data peribadi sensitif memerlukan **kebenaran nyata (explicit consent)**
daripada individu berkenaan. **Tanggungjawab mendapatkan kebenaran itu terletak
pada pertubuhan anda** sebagai pengawal data. Minit menyediakan alat; ia tidak
menggantikan kebenaran.

## 5. Mengapa kami memprosesnya

- Menghasilkan draf minit mesyuarat, resit, pek AGM dan dokumen pematuhan
- Mengeluarkan nombor resit berturutan yang tidak boleh diubah
- Menjawab soalan tentang perlembagaan pertubuhan anda
- Mengira kuota penggunaan AI dan menghalang penyalahgunaan
- Memenuhi kewajipan undang-undang kami

## 6. Pihak ketiga dan pemindahan ke luar negara

Untuk berfungsi, Minit menghantar data kepada pembekal berikut:

| Pembekal | Untuk apa | Lokasi |
|---|---|---|
| **[[Google — Gemini API]]** | membaca foto tulisan tangan, menjana draf | Luar negara |
| **[[Supabase]]** | pangkalan data dan storan fail | **[[region — SAHKAN]]** |
| **[[Vercel]]** | hos aplikasi web | Luar negara |

Pemindahan ke luar negara dilakukan atas dasar **[[dasar undang-undang —
SAHKAN DENGAN PEGUAM]]**, selaras dengan Garis Panduan Pemindahan Data
Peribadi Rentas Sempadan (2025).

**Kami tidak menjual data anda. Kami tidak berkongsi data anda untuk pengiklanan.**

**Peringkat berbayar (sejak Ogos 2026):** akses AI Minit berjalan pada
peringkat API **berbayar**, dan di bawah terma berbayar itu input anda
**tidak digunakan untuk melatih** model pembekal. Walaupun begitu, amalan
kami tetap: hantar seminimum mungkin data peribadi yang tidak perlu —
nombor kad pengenalan hampir tidak pernah diperlukan. Jika pada bila-bila
masa perkhidmatan AI kami kembali kepada peringkat percuma (yang mungkin
menggunakan input untuk latihan), kami akan memaklumkan dan hanya menerima
data contoh/rekaan sepanjang tempoh itu.

## 7. Keselamatan

- Setiap baris data dilindungi oleh *row-level security* mengikut pertubuhan
- Fail disimpan dalam baldi storan **peribadi**, dilaluan mengikut pertubuhan
- Nama penderma **ditutup secara lalai** dalam paparan senarai
- Kunci pelayan tidak pernah dihantar ke pelayar web
- Kandungan dokumen tidak pernah direkod dalam log

## 8. Berapa lama kami simpan

| Data | Tempoh |
|---|---|
| Resit dan minit yang disahkan | **[[selaras kehendak Akta Pertubuhan 1966 — SAHKAN]]** |
| Foto asal yang dimuat naik | **[[tempoh]]** |
| Rekod penggunaan AI | **[[tempoh]]** |
| Akaun | sehingga anda memadamkannya |

Apabila sebuah pertubuhan dipadam, kami memadam baris pangkalan data **dan**
fail storan yang berkaitan.

## 9. Hak anda

Di bawah APDP 2010 (sebagaimana dipinda 2024) anda berhak untuk:

- **mengakses** data peribadi anda
- **membetulkan** data yang tidak tepat
- **menarik balik kebenaran**
- **menghadkan pemprosesan**
- **mudah alih data (data portability)** — meminta data anda dalam format
  yang boleh dibaca mesin

Hubungi **[[emel privasi]]**. Kami akan membalas dalam **[[bilangan]] hari**.

## 10. Pelanggaran data

Jika berlaku pelanggaran data peribadi, kami akan memberitahu Pesuruhjaya
Perlindungan Data Peribadi **dalam masa 72 jam** selepas menyedarinya, dan
memberitahu pertubuhan serta individu yang terjejas jika pelanggaran itu
berkemungkinan menyebabkan kemudaratan yang ketara — seperti dikehendaki oleh
Seksyen 12B APDP.

## 11. Perubahan

Kami akan memaparkan sebarang perubahan penting di dalam aplikasi sebelum ia
berkuat kuasa.

**Versi: [[tarikh]]**

---

# PART 2 — ENGLISH

## 1. Who we are

Minit is operated by **[[legal entity name]]**, **[[registration no.]]**, of
**[[address]]** ("we", "us").

Data protection contact: **[[privacy email]]**

## 2. Two different roles — please read this section

Minit handles two kinds of data, and our legal role is different for each.

**(a) Your account data — we are the DATA CONTROLLER.**
Your email address, which organisations you belong to, your role, and AI usage
records. We decide why and how this is processed.

**(b) Your organisation's documents and records — we are the DATA PROCESSOR.**
Meeting notes, donation ledgers, donor names, phone numbers, IC numbers,
constitutions, committee rosters. **Your organisation is the data controller**
for this information. We process it only on the organisation's behalf and on
its instructions.

> **If you are a donor** and want to know what is held about you, or want it
> deleted — please contact **the organisation that issued your receipt**, not
> us. They are the controller. We will help them fulfil your request.

## 3. What we process

| Type | Examples | Our role |
|---|---|---|
| Account data | email, password (hashed), role | Controller |
| Organisation data | society name, registration no., branches | Controller |
| Uploaded documents | photos of meeting notes, ledger pages, constitution | Processor |
| Donor data | name, phone, amount, purpose, date | Processor |
| Usage records | count of AI actions and dates — **no content** | Controller |

**We do not record the contents of your documents in system logs.** Usage
records contain only an organisation id, a short action code, and a timestamp.

## 4. Sensitive personal data

Some information processed through Minit may be **sensitive personal data**
under Section 4 of the PDPA 2010 — for example, a record of a donation to a
religious organisation may reveal a person's religious beliefs.

Sensitive personal data requires the **explicit consent** of the individual.
**Obtaining that consent is your organisation's responsibility** as the data
controller. Minit provides tooling; it is not a substitute for consent.

## 5. Why we process it

- To draft meeting minutes, receipts, AGM packs and compliance documents
- To issue sequential, non-editable receipt numbers
- To answer questions about your organisation's constitution
- To meter AI usage and prevent abuse
- To meet our own legal obligations

## 6. Third parties and transfers outside Malaysia

To function, Minit sends data to the following providers:

| Provider | Purpose | Location |
|---|---|---|
| **[[Google — Gemini API]]** | reading handwriting, generating drafts | Outside Malaysia |
| **[[Supabase]]** | database and file storage | **[[region — CONFIRM]]** |
| **[[Vercel]]** | web application hosting | Outside Malaysia |

Transfers outside Malaysia are made on the basis of **[[legal basis — CONFIRM
WITH A LAWYER]]**, consistent with the 2025 Cross-Border Personal Data
Transfer Guidelines.

**We do not sell your data. We do not share your data for advertising.**

**Paid tier (since August 2026):** Minit's AI access runs on the **paid**
API tier, and under those paid terms your inputs are **not used to train**
the provider's models. Our practice stays the same regardless: send as
little unnecessary personal data as possible — IC numbers are almost never
needed. If our AI service ever returns to a free tier (which may use inputs
for training), we will say so and accept sample/fictional data only for as
long as that lasts.

## 7. Security

- Every row is protected by row-level security scoped to an organisation
- Files are held in **private** storage buckets, pathed by organisation
- Donor names are **masked by default** in list views
- Server keys are never sent to the browser
- Document contents are never written to logs

## 8. How long we keep it

| Data | Period |
|---|---|
| Confirmed receipts and minutes | **[[per Societies Act 1966 — CONFIRM]]** |
| Original uploaded photos | **[[period]]** |
| AI usage records | **[[period]]** |
| Accounts | until you delete them |

When an organisation is deleted, we delete both the database rows **and** the
associated storage objects.

## 9. Your rights

Under the PDPA 2010 (as amended in 2024) you have the right to:

- **access** your personal data
- **correct** inaccurate data
- **withdraw consent**
- **limit processing**
- **data portability** — request your data in a machine-readable format

Contact **[[privacy email]]**. We will respond within **[[number]] days**.

## 10. Data breaches

If a personal data breach occurs, we will notify the Personal Data Protection
Commissioner **within 72 hours** of becoming aware of it, and notify affected
organisations and individuals where the breach is likely to cause significant
harm — as required by Section 12B of the PDPA.

## 11. Changes

We will show any material change in the app before it takes effect.

**Version: [[date]]**

---

> **Nota pelaksanaan / Implementation note:**
> Terbitkan sebagai \`/privacy\`, tambah laluan itu ke \`PUBLIC_PATHS\` dalam
> \`src/proxy.ts\` (bersama \`/login\`) supaya ia boleh dibaca **sebelum** log
> masuk, dan pautkannya dari borang pendaftaran.
>
> Publish as \`/privacy\`, add that path to \`PUBLIC_PATHS\` in \`src/proxy.ts\`
> (alongside \`/login\`) so it is readable **before** signing in, and link it
> from the sign-up form.
`;

/** Short hash of the text above. This is what a person's consent is recorded
 *  against, so an edited clause is visibly a different version. */
export const PRIVACY_VERSION = "75ad66b1b92a";

/** Both versions together — what goes into the signup consent record. */
export const LEGAL_VERSIONS = {
  terms: TERMS_VERSION,
  privacy: PRIVACY_VERSION,
} as const;
