"use client";

import { useState } from "react";
import Link from "next/link";
import { Download } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tri, useTriText } from "@/components/language-provider";
import { NextStepLink, PageSection } from "@/components/page-section";
import {
  buildWaMeLink,
  receiptWhatsAppMessageBm,
  taxDeductibilityLineBm,
  type RegisterDonation,
} from "@/lib/receipts";
import { formatRm } from "@/lib/minutes-draft";
import { maskName } from "@/lib/mask";
import { downloadFromApi } from "@/lib/download-file";
import { todayIsoMalaysia } from "@/lib/history";
import { DonationEditor } from "./donation-editor";
import { ManualIncomeForm } from "./manual-income";
import { TypeDonations } from "./type-donations";
import { CUSTODY_LABEL, CUSTODY_STYLE } from "./custody-labels";
import { useRegister } from "./register-store";

// ---------------------------------------------------------------------------
// /money/receipts — STEP 2: the register, and turning it into receipts.
//
// This is the page somebody actually opens most days, and before the
// 2026-08-23 split it was the MIDDLE of a 1734-line scroll: to issue one
// receipt you passed the ledger camera on the way in and the month-end tax
// pack on the way out. It now has its own address.
//
// Adding rows by hand lives here too, because a hand-typed gift and a
// photographed one are the same thing once they are in the register — the
// difference is only how they got in.
// ---------------------------------------------------------------------------

export function RegisterAndReceipts() {
  const t = useTriText();
  const {
    donations,
    documentOrgName,
    taxStatus,
    registerCollector,
    receiptsIssued,
    cashInHandCents,
    saveDonation,
    addManualDonation,
    addManualDonations,
    issueReceipts,
    issueBusy,
    issueNotice,
    setError,
  } = useRegister();

  const [editingId, setEditingId] = useState<string | null>(null);
  // PDPA (Hard Rule 5): donor names are MASKED by default in list views.
  // The toggle reveals them only for the current visit — never persisted.
  const [showNames, setShowNames] = useState(false);
  /** True while the irreversible "issue receipts" confirmation is showing. */
  const [confirmIssue, setConfirmIssue] = useState(false);
  /**
   * Which download is in flight.
   *
   * AUDIT FIX (2026-07-28): every file download had NO busy state and no button
   * disabling. Server-side PDF generation plus a network round-trip means
   * seconds of nothing happening after the tap, which reliably makes our users
   * tap again.
   */
  const [downloadBusy, setDownloadBusy] = useState<string | null>(null);

  async function downloadReceiptPdf(d: RegisterDonation) {
    if (!d.receiptNo) return;
    if (downloadBusy) return;
    setError(null);
    setDownloadBusy(`receipt:${d.id}`);
    try {
      await downloadFromApi(
        "/api/receipt-pdf",
        {
          // orgName, taxStatus and confirmedBy are deliberately NOT sent:
          // the server reads them from the signed-in user's organisation so a
          // receipt can never claim the wrong org or a false tax status.
          receiptNo: d.receiptNo,
          donorName: d.donorName,
          amountCents: d.amountCents,
          dateIso: d.donatedAtIso,
          purpose: d.purpose,
          collector: d.collector,
          confirmedOnIso: todayIsoMalaysia(),
        },
        `resit-${d.receiptNo}.pdf`
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setDownloadBusy(null);
    }
  }

  return (
    <PageSection
      step={2}
      titleBm="Daftar derma & jana resit"
      titleZh="捐款登记与开收据"
      titleEn="The register, and issuing receipts"
      summary={
        donations.length === 0 ? (
          <Tri
            bm="Kosong buat masa ini. Baris yang anda sahkan di langkah 1 akan masuk ke sini — atau taip terus di bawah."
            zh="现在还是空的。您在第 1 步确认的行会进到这里 —— 也可以直接在下面打字输入。"
            en="Empty for now. The rows you confirm in step 1 land here — or type them in below."
          />
        ) : (
          <Tri
            bm={`${donations.length} derma dalam daftar. Nombor resit dijana oleh kod, berurutan dan tidak boleh diulang.`}
            zh={`登记簿里有 ${donations.length} 笔捐款。收据号码由程序按顺序生成，不会重复。`}
            en={`${donations.length} donation(s) in the register. Receipt numbers are generated by code, in order, never reused.`}
          />
        )
      }
    >
      <div className="flex flex-col gap-4">
        <p className="text-base text-muted-foreground">
          <Tri
            bm="Nombor berurutan dijana oleh kod, bukan AI."
            zh="编号由程序生成，不是 AI。"
            en="Numbers generated by code, not the AI."
          />
        </p>
        {/* 2026-08-18: this used to be glued onto the end of the sentence
            above with a space. In Chinese that produced one run-on line whose
            second half was about a completely different subject AND in a
            language the reader had not chosen — it read like a mistake.
            The sentence itself is NOT translated on purpose: it is the exact
            legal wording printed on the receipt PDF (CLAUDE.md Hard Rule 3),
            and screen and paper must match word for word. So it now stands on
            its own, labelled as what it is, with the meaning said plainly
            underneath in the reader's language. */}
        <div className="rounded-2xl border-2 border-[color:var(--v2-border)] bg-white/60 p-3 dark:bg-white/5">
          <p className="text-sm font-medium text-muted-foreground">
            <Tri
              bm="Ayat ini dicetak pada setiap resit, tepat seperti di bawah:"
              zh="下面这一句会原样印在每一张收据上："
              en="This sentence is printed on every receipt, exactly as below:"
            />
          </p>
          {/* The org's REAL tax status, resolved on the server, so this line
              always matches what the generated PDF will say. */}
          <p className="mt-1 text-base font-medium">
            {taxDeductibilityLineBm(taxStatus)}
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            {taxStatus === "s44_6" ? (
              <Tri
                bm="Maksudnya: penderma boleh menuntut pelepasan cukai dengan resit ini."
                zh="意思是：捐款人可以用这张收据申报扣税。"
                en="What it means: the donor can claim a tax deduction with this receipt."
              />
            ) : (
              <Tri
                bm="Maksudnya: penderma TIDAK boleh menuntut pelepasan cukai dengan resit ini."
                zh="意思是：捐款人不能用这张收据申报扣税。"
                en="What it means: the donor cannot claim a tax deduction with this receipt."
              />
            )}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          {/* Issuing receipts is IRREVERSIBLE: it locks every amount and
              burns a block of sequential numbers that can never be reused.
              So the button asks once before it fires. */}
          {!receiptsIssued && !confirmIssue && (
            <Button
              onClick={() => setConfirmIssue(true)}
              size="lg"
              className="text-base"
              disabled={issueBusy}
            >
              <Tri bm="Jana resit berurutan" zh="生成正式收据" en="Issue receipts" />
            </Button>
          )}
          {!receiptsIssued && confirmIssue && (
            <div className="flex flex-col gap-2 rounded-lg border border-amber-300 bg-amber-50 p-3">
              <p className="text-sm text-amber-900">
                <Tri
                  bm="Nombor resit tidak boleh dibatalkan atau diubah selepas ini, dan jumlah wang akan dikunci. Teruskan?"
                  zh="收据编号一经生成即无法取消或修改，金额也将锁定。确定继续吗？"
                  en="Receipt numbers cannot be cancelled or changed afterwards, and the amounts are locked. Continue?"
                />
              </p>
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  size="lg"
                  className="text-base"
                  disabled={issueBusy}
                  onClick={() => {
                    setConfirmIssue(false);
                    void issueReceipts();
                  }}
                >
                  {issueBusy ? (
                    <Tri bm="Menjana…" zh="生成中…" en="Issuing…" />
                  ) : (
                    <Tri bm="Ya, jana resit" zh="是，生成收据" en="Yes, issue receipts" />
                  )}
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="text-base"
                  disabled={issueBusy}
                  onClick={() => setConfirmIssue(false)}
                >
                  <Tri bm="Batal" zh="取消" en="Cancel" />
                </Button>
              </div>
            </div>
          )}
          <Link href="/money/history" className="text-sm underline underline-offset-4">
            <Tri bm="Sejarah resit" zh="收据历史" en="Receipt history" /> →
          </Link>
          {/* PDPA: names masked by default; reveal is a deliberate tap */}
          <Button variant="outline" size="sm" onClick={() => setShowNames((v) => !v)}>
            {showNames ? (
              <Tri bm="🙈 Sorok nama" zh="隐藏姓名" en="Hide names" />
            ) : (
              <Tri bm="👁 Tunjuk nama" zh="显示姓名" en="Show names" />
            )}
          </Button>
          {!showNames && (
            <span className="text-sm text-muted-foreground">
              <Tri
                bm="Nama penderma disorok untuk melindungi privasi mereka"
                zh="为保护捐款人隐私，姓名已隐藏"
                en="Donor names are hidden to protect their privacy"
              />
            </span>
          )}
        </div>
        {issueNotice === "saved" && (
          <p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-800">
            <Tri
              bm="Resit disimpan ke sejarah pertubuhan"
              zh="收据已保存到组织历史"
              en="Receipts saved to the organisation's history"
            />
          </p>
        )}
        {issueNotice === "local" && (
          <p className="rounded-md bg-amber-50 px-3 py-2 text-sm text-amber-800">
            <Tri
              bm="Mod demo: nombor dijana setempat sahaja — TIDAK disimpan. Pilih pertubuhan di halaman Pertubuhan untuk menyimpan."
              zh="演示模式：编号仅在本机生成——未保存。请在组织页面选择组织以保存。"
              en="Demo mode: numbers issued locally only — NOT saved. Choose an organisation on the Organisations page to save."
            />
          </p>
        )}
        {issueNotice === "readonly" && (
          <p className="rounded-xl border-2 border-slate-300 bg-slate-50 p-3 text-base font-medium text-slate-800 dark:bg-white/10 dark:text-slate-100">
            <Tri
              bm="Akaun anda ialah akaun juruaudit — boleh melihat sahaja, tidak boleh menjana resit. Minta pentadbir pertubuhan untuk melakukannya."
              zh="您的账号是审计账号，只能查看，不能开收据。请让机构管理员来处理。"
              en="Your account is an auditor account — view only, it cannot issue receipts. Ask an organisation administrator to do it."
            />
          </p>
        )}
        {issueNotice === "reconcile" && (
          <p className="rounded-xl border-2 border-red-300 bg-red-50 p-3 text-base font-semibold text-red-900 dark:bg-red-400/10 dark:text-red-100">
            <Tri
              bm="BERHENTI. Sebahagian rekod mungkin sudah masuk ke pangkalan data dan Minit tidak dapat membersihkannya. JANGAN tekan lagi. Buka “Sejarah resit” dan lihat apa yang sudah ada di sana dahulu."
              zh="请停一下。有部分记录可能已经写进资料库，而 Minit 没能清理干净。请不要重复点击。先打开「收据历史」，看看那边已经有了什么。"
              en="STOP. Some records may already be in the database and Minit could not clean them up. Do NOT tap again. Open “Receipt history” and see what is already there first."
            />
          </p>
        )}
        {issueNotice === "error" && (
          <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-800">
            <Tri
              bm="Tidak pasti sama ada resit telah dijana. JANGAN tekan lagi — semak “Sejarah resit” dahulu."
              zh="无法确定收据是否已生成。请勿重复点击——请先查看“收据历史”。"
              en="We could not confirm whether the receipts were issued. Do NOT tap again — check “Receipt history” first."
            />
          </p>
        )}
        {donations.length === 0 && (
          /* /money had NO empty state at all — it was permanently in demo
             mode with five fictional donors. (2026-07-28 audit.) */
          <div className="rounded-xl border-2 border-dashed p-5 text-base">
            <p className="font-semibold">
              <Tri
                bm="Daftar derma masih kosong."
                zh="捐款登记簿还是空的。"
                en="The donation register is empty."
              />
            </p>
            <p className="mt-1 text-muted-foreground">
              <Tri
                bm="Ambil gambar halaman lejar anda di langkah 1 di atas. AI akan membaca setiap baris, anda sahkan, dan baris yang disahkan masuk ke sini."
                zh="请在上面第 1 步拍下您的账页照片。AI 会逐行读出来，您确认之后，确认过的记录就会进到这里。"
                en="Take a photo of your ledger page in step 1 above. Minit reads each line, you check it, and the checked lines land here."
              />
            </p>
          </div>
        )}
        {/* One card per donation — no sideways scroll */}
        <div className="grid gap-3 sm:grid-cols-2">
          {donations.map((d) => {
            const waLink = d.receiptNo
              ? buildWaMeLink(
                  d.donorPhone,
                  receiptWhatsAppMessageBm({
                    orgName: documentOrgName,
                    receiptNo: d.receiptNo,
                    donorName: d.donorName,
                    amountCents: d.amountCents,
                    dateIso: d.donatedAtIso,
                    purpose: d.purpose,
                    taxStatus,
                  })
                )
              : null;
            return (
              <div key={d.id} className="rounded-lg border p-4">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <p className="font-medium">
                      {showNames ? d.donorName : maskName(d.donorName)}
                      {d.source === "manual" && (
                        <Badge
                          variant="outline"
                          className="ml-2 border-slate-300 bg-slate-100 text-slate-700"
                        >
                          <Tri bm="manual" zh="手动" en="manual" />
                        </Badge>
                      )}
                    </p>
                    <p className="font-mono text-sm text-muted-foreground">
                      {d.receiptNo ?? t("belum ada resit", "还没有收据", "no receipt yet")}
                    </p>
                  </div>
                  <span className="font-semibold tabular-nums">{formatRm(d.amountCents)}</span>
                </div>
                <div className="mt-2">
                  <Badge variant="outline" className={CUSTODY_STYLE[d.custodyStatus]}>
                    <Tri {...CUSTODY_LABEL[d.custodyStatus]} />
                  </Badge>
                </div>
                <div className="mt-3 flex flex-wrap gap-2">
                  {!d.receiptNo && editingId !== d.id && (
                    <Button variant="outline" onClick={() => setEditingId(d.id)}>
                      ✏️ <Tri bm="Ubah butiran" zh="修改资料" en="Edit details" />
                    </Button>
                  )}
                  {d.receiptNo && (
                    <Button
                      variant="outline"
                      onClick={() => downloadReceiptPdf(d)}
                      disabled={downloadBusy !== null}
                    >
                      {downloadBusy === `receipt:${d.id}` ? (
                        <Tri bm="Menyiapkan…" zh="正在准备…" en="Preparing…" />
                      ) : (
                        <>
                          <Download className="h-5 w-5" strokeWidth={2} />
                          <Tri bm="Muat turun resit" zh="下载收据" en="Download receipt" />
                        </>
                      )}
                    </Button>
                  )}
                  {waLink ? (
                    <Button variant="outline" asChild>
                      <a href={waLink} target="_blank" rel="noopener noreferrer">
                        📱 <Tri bm="Hantar WhatsApp" zh="用 WhatsApp 发送" en="Send on WhatsApp" />
                      </a>
                    </Button>
                  ) : (
                    d.receiptNo && (
                      <span className="self-center text-base text-muted-foreground">
                        {t(
                          "Tiada nombor telefon — tekan “Ubah butiran” untuk menambahnya, kemudian hantar melalui WhatsApp.",
                          "没有电话号码 —— 按「修改资料」补上，就可以用 WhatsApp 发送。",
                          "No phone number — tap “Edit details” to add one, then you can send it on WhatsApp.",
                        )}
                      </span>
                    )
                  )}
                </div>
                {editingId === d.id && (
                  <DonationEditor
                    donation={d}
                    onSave={saveDonation}
                    onCancel={() => setEditingId(null)}
                  />
                )}
                {d.receiptNo && (
                  <p className="mt-2 text-sm text-muted-foreground">
                    🔒{" "}
                    <Tri
                      bm="Dikunci untuk audit"
                      zh="已锁定以供审计"
                      en="Locked for the audit trail"
                    />
                  </p>
                )}
              </div>
            );
          })}
        </div>

        {/* Manual entry lives INSIDE the register step now, not as a fifth
            top-level card competing with the photo flow. It is the fallback for
            a donation that was never written on paper. */}
        {/* Two shapes of "there was no paper", because they are genuinely
            different jobs: ONE gift with a category and a note (rental, a
            grant, cash handed over) — and a COLLECTION, forty people at
            RM10 each, where the only thing that varies row to row is a name
            and an amount. J, 2026-08-22: 賬單如果捐錢人多的話會到很多. */}
        <TypeDonations
          onAddMany={addManualDonations}
          defaultCollector={registerCollector}
        />
        <ManualIncomeForm onAdd={addManualDonation} defaultCollector={registerCollector} />
      </div>

      <NextStepLink
        href="/money/custody"
        labelBm="Ke serahan wang tunai"
        labelZh="去交现金给总会"
        labelEn="On to handing over the cash"
        blockedReason={
          !receiptsIssued ? (
            <Tri
              bm="Jana resit dahulu — wang hanya boleh diserahkan selepas setiap derma ada nombor resit, kalau tidak tiada apa-apa untuk diikat pada serahan itu."
              zh="请先开收据 —— 只有每笔捐款都有收据号码之后才能交接，否则交出去的钱没有凭据可以对。"
              en="Issue the receipts first — cash can only be handed over once every donation has a receipt number, otherwise there is nothing to tie the hand-over to."
            />
          ) : cashInHandCents === 0 ? (
            <Tri
              bm="Tiada wang tunai yang tertunggak. Hujung bulan, muat turun fail cukai."
              zh="没有还没交出去的现金。到月底再下载税务文件就好。"
              en="No cash outstanding. At month end, download the tax file."
            />
          ) : undefined
        }
      />
    </PageSection>
  );
}
