// npm run legal:sync  —  copy legal/*.md into the app bundle, verbatim.
//
// WHY A GENERATED FILE AND NOT fs.readFileSync IN THE PAGE
// /terms and /privacy have to show the documents in legal/ word for word. A
// server component COULD read them at request time, but on Vercel a file is
// only in the deployment if Next's tracer noticed it, and a path built at
// runtime is exactly what the tracer cannot see. A missing privacy notice in
// production is not a rendering bug — PDPA s.7 requires that notice to be
// given, in Bahasa Malaysia and English, before personal data is collected.
// So the text is compiled in, and this script is how it gets there.
//
// The lawyer (or J) edits legal/*.md as usual, then runs:
//     npm run legal:sync
// It rewrites src/legal/documents.ts. Commit both. `npm test` fails if they
// have drifted apart (src/legal/documents.test.ts), so a legal edit cannot ship
// half-applied.

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));

const DOCS = [
  { key: "TERMS", file: "legal/terms-of-use-BM-EN.md" },
  { key: "PRIVACY", file: "legal/privacy-notice-BM-EN.md" },
];

/** The version a person agrees to is the CONTENT, not a number somebody
 *  remembered to bump: a short hash of the file itself. Change a clause and the
 *  version changes, so consent recorded against the old text is visibly old. */
function version(text) {
  return createHash("sha256").update(text, "utf8").digest("hex").slice(0, 12);
}

const parts = DOCS.map(({ key, file }) => {
  const text = readFileSync(path.join(root, file), "utf8").replace(/\r\n/g, "\n");
  return { key, file, text, version: version(text) };
});

const escape = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out = `// GENERATED BY \`npm run legal:sync\` — DO NOT EDIT BY HAND.
// Source of truth: ${DOCS.map((d) => d.file).join(", ")}.
// Edit the markdown, run the script, commit both. src/legal/documents.test.ts
// fails if this file and the markdown disagree.
//
// Why this exists at all: src/app/(legal)/ must show these documents word for
// word, and a file read at request time may not be in the deployment. See
// scripts/sync-legal.mjs.

${parts
  .map(
    (p) => `/** ${p.file} — verbatim. */
export const ${p.key}_MARKDOWN = \`${escape(p.text)}\`;

/** Short hash of the text above. This is what a person's consent is recorded
 *  against, so an edited clause is visibly a different version. */
export const ${p.key}_VERSION = "${p.version}";
`,
  )
  .join("\n")}
/** Both versions together — what goes into the signup consent record. */
export const LEGAL_VERSIONS = {
  terms: TERMS_VERSION,
  privacy: PRIVACY_VERSION,
} as const;
`;

mkdirSync(path.join(root, "src/legal"), { recursive: true });
writeFileSync(path.join(root, "src/legal/documents.ts"), out, "utf8");

for (const p of parts) {
  const placeholders = (p.text.match(/\[\[[^\]]*\]\]/g) ?? []).length;
  console.log(
    `${p.file}  ->  ${p.key}_MARKDOWN  (${p.text.length} chars, version ${p.version})` +
      (placeholders ? `   ⚠ ${placeholders} unfilled [[ ]] placeholders` : ""),
  );
}
console.log("\nwrote src/legal/documents.ts");
